baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'GoboLinux Documentation'
theme = "hugo-theme-relearn"
disablePathToLower = true

# Required in cases the project is *not* hosted under the root directory of the domain
relativeURLs = false

[outputs]
  home = [ "html", "rss", "print"]
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']

[params]
  version="v017.01"
  editURL = "https://github.com/gobolinux/Documentation/edit/master/content/"
  themeVariant = "gobolinux"
  titleSeparator = "|"
  disableLandingPageButton = true
  showVisitedLinks = true
  disableInlineCopyToClipBoard = true
  disableSeoHiddenPages = true
  alwaysopen = false
  collapsibleMenu = true
  [params.author]
    author = "NEONsys.org"
  [[params.versions]]
    baseURL = "http://localhost:1313/"
    identifier = "v017.01"
    title = "v017.01 (latest)"
    isLatest = true
  [[params.versions]]
    baseURL = "http://localhost:1314/v017/"
    identifier = "v017"
    title = "v017"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false
  [markup.highlight]
    style = "rrt" # choose a color theme or create your own
    guessSyntax = false # if set to true, avoid unstyled code if no language was given but mermaid code fences will not work anymore

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-globe'></i> Homepage"
url = "https://gobolinux.org/"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> Repository"
url = "https://github.com/gobolinux"
weight = 2

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-users'></i> Community"
url = "https://gobolinux.discourse.group/"
weight = 3

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-book'></i> Recipes"
url = "https://github.com/gobolinux/Recipes"
weight = 4

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-download'></i> Download ISO"
url = "https://gobolinux.org/downloads.html"
weight = 5

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i> Showcases"
url = "https://gobolinux.org/screenshots.html"
weight = 6

sidebarfootermenus = []

[[sidebarheadermenus]]
  type = 'custom'

  [[sidebarheadermenus.elements]]
    type = 'languageswitcher'

  [[sidebarheadermenus.elements]]
    type = 'historyclearer'
  
  [[sidebarfootermenus.elements]]
    type = 'versionswitcher'

[[sidebarheadermenus]]
  type = 'divider'

[[sidebarmenus]]
  type = 'page'